name: Approve Pull Request on Comment

on:
  issue_comment:
    types: [created, edited]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: ${{ github.event.issue.pull_request && contains(fromJson('["lgtm", "LGTM"]'), github.event.comment.body) }}
    steps:
      - uses: hmarr/auto-approve-action@v3
        with:
          review-message: "Auto approved automated PR"
          pull-request-number: ${{ github.event.issue.number }}
