name: Approve Pull Request on Review Comment

on:
  pull_request_review:
    types: [submitted, edited]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: ${{ contains(fromJson('["lgtm", "LGTM"]'), github.event.review.body) }}
    steps:
      - uses: hmarr/auto-approve-action@v3
        with:
          review-message: "Auto approved automated PR"
          pull-request-number: ${{ github.event.pull_request.number }}
